train:
  teacher_path: 'output/checkpoints/gtrsb_teacher83.pt'
  score_path: 'output/checkpoints/gtrsb_score.pt'
  student_path: 'output/checkpoints/gtrsb_student87.pt'

  batch_size: 128

#  train_teacher:
#   epoch: 100
#   lr: 0.001
#   log:
#     path: 'output/log/gtrsb_teacher.log'
#     log_every: 30
#   save_every: 7
#   checkpoint_path: 'output/checkpoints/gtrsb_teacher'
#   sample_path: 'output/images/gtrsb'
#
#  train_score:
#   batch_size: 128
#   epoch: 1
#   datasize: 800000
#   lr: 0.001
#   log:
#     path: 'output/log/gtrsb_score.log'
#     log_every: 20
#   save_every: 2
#   checkpoint_path: 'output/checkpoints/gtrsb_score'

#  train_students:
#   epoch: 100
#   lr: 0.001
#   log:
#     path: 'output/log/gtrsb_student.log'
#     log_every: 10
#   save_every: 4
#   checkpoint_path: 'output/checkpoints/gtrsb_student'
#   sample_path: 'output/images/gtrsb_student'
#

  student:
    src: [0,1,2,3]
    dst: [0,1,2,3,8,9,10,11]


GA:
  fit_func:
    data_size: 4000
    batch_size: 40
    lr: 0.0005
    iter_limit: 500

  instance:
    num_generations: 16
    num_genes: 8
    num_parents_mating: 4
    sol_per_pop: 10

    init_range_low: 0
    init_range_high: 1

    parent_selection_type: 'sss'
    keep_parents: 2
    crossover_type: 'uniform'

    mutation_type: 'scramble'
    # mutation_percent_genes: 2
    mutation_num_genes: 2
  upper_bound: 0.1
  fitness_fig_path: 'output/images/fitness/stl'

model:
  pooling_kernel: [4, 4]
  encoder_output_size: 6
  color_channels: 3
  num_classes: 12
# num_classes should be equal to len(targets)

# number of image per class
# [(210, 0), (2220, 1), (2250, 2), (1410, 3), (1980, 4), (1860, 5), (420, 6), (1440, 7), (1410, 8), (1470, 9), (2010, 10), (1320, 11), (2100, 12), (2160, 13), (780, 14), (630, 15), (420, 16), (1110, 17), (1200, 18), (210, 19), (360, 20), (330, 21), (390, 22), (510, 23), (270, 24), (1500, 25), (600, 26), (240, 27), (540, 28), (270, 29), (450, 30), (780, 31), (240, 32), (689, 33), (420, 34), (1200, 35), (390, 36), (210, 37), (2070, 38), (300, 39), (360, 40), (240, 41), (240, 42)]
data:
  name: 'GTRSB'
  root: 'data/GTSRB/Final_Training/Images'
  transform: 'GTRSB_Transform'

optim:
  lr: 0.001
