train:
  train_teacher:
    epoch: 10
    lr: 0.001
  batch_size: 10

data:
  name: 'STL'
  root: 'data/STL'
  transform: 'MNIST_train_trans'
  targets: [0,1,2,3]
  download: True

model:
  pooling_kernel: [4, 4]
  encoder_output_size: 6
  color_channels: 3

  
optim:
  lr: 0.001
